name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install imagemagick
        run: sudo apt install ghostscript
      - name: Change imagemagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          SRC="name=${DQT}disk${DQT} value=${DQT}1GiB${DQT}"
          RPL="name=${DQT}disk${DQT} value=${DQT}8GiB${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
      - name: Install typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.10.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xJf typst-x86_64-unknown-linux-musl.tar.xz && mv typst-x86_64-unknown-linux-musl/typst .
          chmod +x typst
      - name: Compile CVs
        run: |
          ./typst compile --font-path ./fonts cv_en.typ
          ./typst compile --font-path ./fonts cv_de.typ
      - name: Convert pdf to png
        run: |
          magic -density 900 -background white -alpha off -resize 50% cv_en.pdf cv_en.png
          magic -density 900 -background white -alpha off -resize 50% cv_de.pdf cv_de.png
      - uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: |
            cv_en.pdf
            cv_de.pdf
            cv_en.png
            cv_de.png
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: |
            cv_en.pdf
            cv_de.pdf
            cv_en.png
            cv_de.png
