name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install typst
        run: |
          echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk add --no-cache typst
      - name: Compile CVs
        run: |
          typst compile cv_en.typ
          typst compile cv_de.typ
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.2          
