name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install xz-utils
        run: sudo apt update && sudo apt install xz-utils wget
      - name: Install typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.10.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xJf typst-x86_64-unknown-linux-musl.tar.xz && mv typst-x86_64-unknown-linux-musl typst
          chmod +x typst
      - name: Compile CVs
        run: |
          ./typst compile cv_en.typ
          ./typst compile cv_de.typ
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.2          
