name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install imagemagick
        run: sudo apt install imagemagick
      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
      - name: install typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.10.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xJf typst-x86_64-unknown-linux-musl.tar.xz && mv typst-x86_64-unknown-linux-musl/typst .
          chmod +x typst
      - name: Compile CVs
        run: |
          ./typst compile --font-path ./fonts cv_en.typ
          ./typst compile --font-path ./fonts cv_de.typ
      - name: convert pdf to png
        run: |
          convert -density 900 -background white -alpha off cv_en.pdf -quality 90 cv_en.png
          convert -density 900 -background white -alpha off cv_de.pdf -quality 90 cv_de.png
      - uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: |
            cv_en.pdf
            cv_de.pdf
            cv_en.png
            cv_de.png
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: |
            "*.pdf"
            "*.png"
