name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.10.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xJf typst-x86_64-unknown-linux-musl.tar.xz && mv typst-x86_64-unknown-linux-musl/typst .
          chmod +x typst
      - name: Compile CVs
        run: |
          ./typst compile --font-path ./fonts cv_en.typ
          ./typst compile --font-path ./fonts cv_de.typ
      - uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: |
            *.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
